### ISSUE TITLE
Road map to first CRAN release

### ISSUE THREAD

**Issue by philipp-baumann** [spectral-cockpit/opusreader2#89]
I consider those points as todos before we submit to CRAN first time (meaning this issue is to consolidate in one place):

- [ ] Complete the main vignette #86 
- [ ] Incorporate helper options to read example files that are shipped with package #69 
- [ ] Add basic plotting methods for `opusreader2` and `list_opusreader2`
- [ ] Implement basic metadata extraction features: #44 #59 #66

Have I forgotten anything relevant? cc @ThomasKnecht

**Comment by philipp-baumann** [comment]
- [ ] Skim `test_data`.
